name: $(Build.BuildId)

variables:
- name: 'AppVersion'
  value: '1.0.[yyyyWW].*'
- name: 'dockerimage'
  value: 'mcr.microsoft.com/businesscentral/onprem:1904-cu1-se'
- name: 'TestFilter'
  value: '50100..50149'
- name: 'bclicense'
  value: '.\license\license.flf'

trigger:
 - master

resources:
 - repo: self
 
pool:
  name: 'Hosted VS2017'

steps:
- checkout: self
  clean: true

- task: ALOpsDockerStart@1
  inputs:
    docker_image: $(dockerimage)
    memory_gb: 4
    docker_pull: false

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bclicense) 
   
- task: ALOpsAppCompiler@1
  inputs:
    usedocker: true
    nav_app_version: $(AppVersion)
    failed_on_warnings: true    

- task: ALOpsAppPublish@1
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 

- task: ALOpsAppTest@1
  inputs:
    usedocker: true
    import_testtoolkit: true
    import_action: "Overwrite"
    testfilter: $(TestFilter)
    show_available_tests: true
    continueOnError: true    

- task: PublishTestResults@2
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '$(System.DefaultWorkingDirectory)\TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

- task: ALOpsDockerRemove@1
  enabled: true
  condition: always()    
    
